# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main, test ]
  pull_request:
    branches: [ main, test ]

jobs:
  
  build:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
    strategy:
      matrix:
        node-version: [12.x, 14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      env:
        MY_SECRET: ${{ secrets.MY_SECRET }}
      with:
        node-version: ${{ matrix.node-version }}
    - id: step1  
      run: npm ci
    - run: |
        if [ "$MY_SECRET" -eq "ABCD" ]
        then
          echo "Got secret"
        fi
        echo "hello"
    - run: node index
    - run: npm test
